services:
  php:
    build: .
    volumes:
      - ./laravel-app:/var/www/app
    ports:
      - "9000:9000"
  
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  
  mysql:
    image: mysql:8.0
    volumes:
      - dbdata:/var/www/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_HOST: mysql
    depends_on:
      - mysql
  
  node:
    image: node:24
    working_dir: /var/www/app
    volumes:
      - ./laravel-app:/var/www/app
      - ./vue-project:/var/www/app
    ports:
      - "5173:5173"
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - php
    
volumes:
  dbdata:

